name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #      - name: Set up Go 1.17
      #        uses: actions/setup-go@v2
      #        with:
      #          go-version: 1.17
      #      - name: set go proxy
      #        run: go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,direct
      #      - name: go build
      #        run: go build -tags musl -ldflags="-w -s" -o zhimiao-app
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          name: zhimiaox/git-robot
          username: mail@xiaoliu.org
          password: ${{ secrets.DOCKER_PWD }}
          tags: latest
      - name: deploy-st01
        uses: appleboy/ssh-action@master
        with:
          host: st01.zhimiaox.cn
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker login -u mail@xiaoliu.org -p ${{ secrets.DOCKER_PWD }} registry.cn-hangzhou.aliyuncs.com
            docker ps
            docker pull registry.cn-hangzhou.aliyuncs.com/zhimiaox/git-robot:latest
            docker rm -f git-robot-dev | true
            docker run -d --name git-robot-dev \
            -v ~/data:/zhimiao/data \
            registry.cn-hangzhou.aliyuncs.com/zhimiaox/git-robot:latest
            docker ps
            docker logout

